substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  name: proxy
  friendly_name: Proxy
  comment: ESPHome proxy tuned for Bermuda
  name_add_mac_suffix: "True"  # Adds the last 4 characters of the MAC address to the name.
  baud_rate: "0"  # If you need serial debugging, override this to 115200 or similar.
  ble_interval: 320ms
  ble_window: 300ms
  proxy_active_scan: "True"  # Set to false to avoid requesting scan info for device names etc

packages:
  Bermuda.include_common: github://agittins/bermuda-proxies/packages/bermuda-proxy-include-common.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  name_add_mac_suffix: ${name_add_mac_suffix}

esp32:
  board: wemos_d1_mini32

ota:
  platform: esphome


wifi:
  domain: .local
  reboot_timeout: 15min
  power_save_mode: LIGHT
  fast_connect: false
  enable_btm: false
  enable_rrm: false
  passive_scan: false
  enable_on_boot: true

  networks:
    - ssid: ${wifi_ssid}
      password: ${wifi_password}
  ap:
    ssid: "${name} Fallback"
    password: "fallback1234"
    ap_timeout: 1min
